TARGET=int_size

main:
	g++ -Wall -o a.out $(TARGET).cpp
b:
	g++ -Wall -o a.out break.cpp
nest:
	g++ -Wall -o a.out nest_for_break.cpp
stoi:
	g++ -Wall -o a.out stoi_l.cpp
neg_rem:
	g++ -Wall -o a.out neg_remainder.cpp